Repository BamaCharanChhandogi/READMEasy, pull requests merged in 2024-10, with the labels that each got.

#7 Update App.jsx
  src/App.jsx
Labels: gssoc, gssoc-ext, hacktoberfest-accepted, level2

#23 Fix validation errors not displaying on README Generator form #14
  src/components/InputForm.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#47 Added Contributing.md File
  CONTRIBUTING.md
Labels: gssoc-ext, level1

#54 Added feature Scroll to Top of Website
  src/App.jsx
Labels: gssoc-ext, level1

#55 Editable Generated Content Feature Implemented
  src/components/EditableOutput.jsx
  src/components/Home.jsx
Labels: gssoc-ext, level3

#59 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#63 Profile Readme Implemented Edit + HTML Rendering
  package-lock.json
  package.json
  src/components/EditableOutput.jsx
  src/components/Home.jsx
  src/components/OutputDisplay.jsx
  src/hooks/GitHubProfileGenerator.jsx
  src/hooks/useReadmeGenerator.jsx
Labels: gssoc-ext, level3

#64 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc-ext, level1

#73 Enhanced the UI/UX of Profile Generator
  src/components/ProfileForm.jsx
Labels: gssoc-ext, level2

#83 Added Responsive Navbar
  src/App.jsx
  src/components/Navbar.jsx
Labels: gssoc-ext, level2

#85 added github star feature #68
  package-lock.json
  package.json
  src/App.jsx
  src/components/Navbar.jsx
  src/components/StarFork.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#92 Adding Issues Templates for Contributor
  .github/ISSUE_TEMPLATE/bug_report_template.md
  .github/ISSUE_TEMPLATE/custom_issue_template.md
  .github/ISSUE_TEMPLATE/feature_request_template.md
Labels: gssoc-ext, hacktoberfest-accepted, level2

#78 Feature : Implemented an interactive FAQ section on the homepage for …
  src/App.jsx
  src/components/FAQ.jsx
  src/components/Navbar.jsx
  src/data/faqData.json
Labels: gssoc-ext, level2

#88 Issue #82 : Add Stack Selection and Pre-Fill Options with Enhanced UI in InputForm Component
  src/components/InputForm.jsx
Labels: gssoc-ext, level2

#108 Added Table to Display Repository Statistics in README.md
  README.md
Labels: gssoc-ext, level1

#110 3dot/hamburger menu fixed that crashed in mobile view | Issue #98
  src/components/Navbar.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#106 Added hover effect and animation to logo and underline effect to nav items
  src/components/Navbar.css
  src/components/Navbar.jsx
Labels: gssoc-ext, level2

#115 added chatbot for enhanced user experience
  index.html
  src/App.jsx
Labels: gssoc-ext, level3

#116 Toolbar + Shortcut keys For Markdown Editor
  package-lock.json
  package.json
  src/components/EditableOutput.jsx
  src/components/MarkdownToolbar.jsx
  src/components/OutputDisplay.jsx
Labels: gssoc-ext, level3
